---
layout: post
title: git push 报错"error inflate data stream error"
tags: [git]
categories: [Wiki]
---

## git push 报错

报错如下：

```shell
jay:qingchen177.github.io (master*) $ git push --verbose
Pushing to github.com:/qingchen177/qingchen177.github.io.git
Enumerating objects: 21, done.
Counting objects: 100% (21/21), done.
Delta compression using up to 10 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (13/13), 617.51 KiB | 1.64 MiB/s, done.
Total 13 (delta 8), reused 5 (delta 0), pack-reused 0
remote: error: inflate: data stream error (invalid stored block lengths)
remote: fatal: pack has bad object at offset 1397: inflate returned -3
error: remote unpack failed: index-pack failed
To github.com:/qingchen177/qingchen177.github.io.git
 ! [remote rejected] master -> master (failed)
error: failed to push some refs to 'github.com:/qingchen177/qingchen177.github.io.git'
```

### 解决方案

`git fsck --full`啥错误没有

网上搜了蛮多的，试了很多种，都是没用，最终莫名其妙解决了，以下是我觉得我按照下面步骤解决成功了

1. 备份项目
2. 删除本地项目
3. 重新克隆远程项目
4. pycharm清除全部缓存
5. 网络代理全部重新关闭/打开

提交新代码成功了

但是我一开始在公司是不可以的，回到家试了一下也不行，折腾了一段时间别的，再提交又可以了，可能和github那边也有关系？
